
import { useState } from "react"
import type { Metadata } from "next";
import localFont from "next/font/local";
import { Nunito_Sans, Edu_VIC_WA_NT_Beginner } from 'next/font/google';
import './fonts/fonts.css'; // Asegúrate de que la ruta sea correcta
import ActionButtonPlay from "@/components/ActionButtonPlay/ActionButtonPlay";

import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const edu_sans_int = Edu_VIC_WA_NT_Beginner({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-edu_sans_int",
  weight: ["600", "700"],
});

const distantStroke = localFont({
  src: "./fonts/Distant_Stroke.otf",
  variable: "--font-distant-stroke",
  weight: "normal", // Ajusta el peso según sea necesario
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className="antialiased relative">
        {children}
        <ActionButtonPlay />
      </body>
    </html>
  );
}
