
import { useState } from "react"
import type { Metadata } from "next";
import localFont from "next/font/local";
import './fonts/fonts.css'; // Asegúrate de que la ruta sea correcta
import ActionButtonPlay from "@/components/ActionButtonPlay/ActionButtonPlay";

import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});


const distantStroke = localFont({
  src: "./fonts/Distant_Stroke.otf",
  variable: "--font-distant-stroke",
  weight: "normal", // Ajusta el peso según sea necesario
});

export const metadata: Metadata = {
  title: "Baby Shower 😊",
  description: "Generated by Henry Pardo",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className="antialiased relative bg-[url('/bg/bg1.png')] bg-cover bg-center min-h-screen">
        {children}
        <ActionButtonPlay />
      </body>
    </html>
  );
}
